drop table budynki;
drop table oswietlenie;
drop table zielen;

CREATE TABLE oswietlenie (
id NUMBER CONSTRAINT oswietlenie_PK PRIMARY KEY,
symbol VARCHAR2(6) NOT NULL,
opis VARCHAR2(50),
wysokosc NUMBER(2) NOT NULL,
geometria SDO_GEOMETRY NOT NULL);

INSERT INTO oswietlenie VALUES(
1,
'L_1',
'LATARNIA 1',
12,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(10, 17, NULL),
NULL,
NULL)
);
INSERT INTO oswietlenie VALUES(
2,
'L_2',
'LATARNIA 2',
8,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(13, 15, NULL),
NULL,
NULL)
);
INSERT INTO oswietlenie VALUES(
3,
'L_3',
'LATARNIA 3',
8,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(6, 15, NULL),
NULL,
NULL)
);
INSERT INTO oswietlenie VALUES(
4,
'L_4',
'LATARNIA 4',
8,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(5, 11, NULL),
NULL,
NULL)
);
INSERT INTO oswietlenie VALUES(
5,
'L_5',
'LATARNIA 5',
8,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(5, 5, NULL),
NULL,
NULL)
);
INSERT INTO oswietlenie VALUES(
6,
'L_6',
'LATARNIA 6',
8,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(13, 5, NULL),
NULL,
NULL)
);
INSERT INTO oswietlenie VALUES(
7,
'L_7',
'LATARNIA 7',
12,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(10, 2, NULL),
NULL,
NULL)
);
INSERT INTO USER_SDO_GEOM_METADATA VALUES(
'OSWIETLENIE',
'GEOMETRIA',
SDO_DIM_ARRAY(
SDO_DIM_ELEMENT('X', 0, 29, 0.1),
SDO_DIM_ELEMENT('Y', 0, 19, 0.1)
),
NULL -- SRID
);
SELECT id, o.geometria.ST_IsValid() 
FROM oswietlenie o
ORDER BY id;
CREATE INDEX oswietlenie_spatial_index
ON oswietlenie (geometria)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
select * from oswietlenie;

CREATE TABLE drogi_chodniki (
id NUMBER CONSTRAINT drogi_chodniki_PK PRIMARY KEY,
symbol VARCHAR2(6) NOT NULL,
opis VARCHAR2(50),
nawierzchnia VARCHAR2(50) NOT NULL,
geometria SDO_GEOMETRY NOT NULL);

INSERT INTO drogi_chodniki VALUES(
1,
'DR_GLW',
'DROGA DOJAZDOWA',
'ASFALT',
SDO_GEOMETRY(
2002,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1, 2, 1),
SDO_ORDINATE_ARRAY(0,1,15,1)
)
);
INSERT INTO drogi_chodniki VALUES(
2,
'CH_A',
'CHODNIK A',
'P£YTY CHODNIKOWE',
SDO_GEOMETRY(
2002,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1, 2, 1),
SDO_ORDINATE_ARRAY(14,1,14,16)
)
);
INSERT INTO drogi_chodniki VALUES(
3,
'CH_B',
'CHODNIK B',
'P£YTY CHODNIKOWE',
SDO_GEOMETRY(
2002,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1, 2, 1),
SDO_ORDINATE_ARRAY(14,7.5,8.5,7.5,8.5,12.5,14,12.5)
)
);

INSERT INTO drogi_chodniki VALUES(
4,
'CH_C',
'CHODNIK C',
'KOSTKA BRUKOWA',
SDO_GEOMETRY(
2002,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1, 4, 3,1,2,1,3,2,2,7,2,1),
SDO_ORDINATE_ARRAY(14,4,6,4,0,10,6,16,14,16)
)
);
select id,o.geometria.ST_IsValid()
from drogi_chodniki o
ORDER BY id;

CREATE INDEX drogi_chodniki_spatial_index
ON drogi_chodniki (geometria)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
select * from drogi_chodniki;

CREATE TABLE budynki (
id NUMBER CONSTRAINT budynki_PK PRIMARY KEY,
symbol VARCHAR2(6) NOT NULL,
opis VARCHAR2(50),
ulica VARCHAR2(30) NOT NULL,
numer VARCHAR2(5),
geometria SDO_GEOMETRY NOT NULL);

INSERT INTO budynki VALUES(
1,
'ŒM_1',
'ŒMIETNIK',
'TRUSKAWKOWA',
NULL,
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,3),
SDO_ORDINATE_ARRAY(8,3,10,4)
)
);
INSERT INTO budynki VALUES(
2,
'BL_A',
'BLOK A',
'TRUSKAWKOWA',
'8/10',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,1),
SDO_ORDINATE_ARRAY(12,15,6,15,6,5,12,5,12,7,8,7,8,13,12,13,12,15)
)
);
INSERT INTO budynki VALUES(
3,
'S',
'SKLEP',
'TRUSKAWKOWA',
'12/14',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,1,15,2003,1),
SDO_ORDINATE_ARRAY(4,7,5,8,5,10,4,11,2,11,2,7,4,7,3,8,4,9,4,8,3,8)
)
);
select id,o.geometria.ST_IsValid()
from budynki o
ORDER BY id;

CREATE INDEX budynki_spatial_index
ON budynki (geometria)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
select * from budynki;

CREATE TABLE zielen (
id NUMBER CONSTRAINT zielen_PK PRIMARY KEY,
symbol VARCHAR2(6) NOT NULL,
opis VARCHAR2(50),
geometria SDO_GEOMETRY NOT NULL);

INSERT INTO zielen VALUES(
1,
'K_1',
'KLOMB 1',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,4),
SDO_ORDINATE_ARRAY(6,2.5,5.5,3,5,2.5)
)
);

INSERT INTO zielen VALUES(
2,
'K_2',
'KLOMB 2',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,4),
SDO_ORDINATE_ARRAY(12,2.5,11.5,3,11,2.5)
)
);

INSERT INTO zielen VALUES(
3,
'K_3',
'KLOMB 3',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,4),
SDO_ORDINATE_ARRAY(6,17.5,5.5,18,5,17.5)
)
);
INSERT INTO zielen VALUES(
4,
'K_4',
'KLOMB 4',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,4),
SDO_ORDINATE_ARRAY(12,17.5,11.5,18,11,17.5)
)
);
INSERT INTO zielen VALUES(
5,
'PZ',
'TEREN ZIELONY Z PLACEM ZABAW',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1005,2,  1,2,1,  7,2,2),
SDO_ORDINATE_ARRAY(11,8,13,8,13,12,11,12,9,10,11,8)
)
);
select id,o.geometria.ST_IsValid()
from zielen o
ORDER BY id;

CREATE INDEX zielen_spatial_index
ON zielen (geometria)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
select * from zielen;

INSERT INTO budynki VALUES(
5,
'T1',
'TRYBUNA',
'TRUSKAWKOWA',
'11/10',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,1),
SDO_ORDINATE_ARRAY(15,4,15,13,17,13,17,4)
)
);
INSERT INTO budynki VALUES(
6,
'T2',
'TRYBUNA',
'TRUSKAWKOWA',
'11/10',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,1),
SDO_ORDINATE_ARRAY(25,4,25,13,27,13,27,4)
)
);

INSERT INTO budynki VALUES(
8,
'G',
'GAZOWNIA',
'TRUSKAWKOWA',
'11/10',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,1),
SDO_ORDINATE_ARRAY(2,16,2,18,4,18,4,16)
)
);

INSERT INTO budynki VALUES(
9,
'R',
'RSCLUB',
'TRUSKAWKOWA',
'12/14',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1003,1),
SDO_ORDINATE_ARRAY(16,15,14,16,14,19,19,19,19,17,16,17,16,14)
)
);

INSERT INTO budynki VALUES(
10,
'R',
'RSCLUB',
'TRUSKAWKOWA',
'12/14',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1005,2,  1,2,1,  7,2,2),
SDO_ORDINATE_ARRAY(24,6,24,9,18,9,18,6,22,3,24,6)
)
);

INSERT INTO budynki VALUES(
11,
'R',
'RSCLUB',
'TRUSKAWKOWA',
'12/14',
SDO_GEOMETRY(
2003,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1,1005,2,  1,2,1,  7,2,2),
SDO_ORDINATE_ARRAY(24,11,24,9,18,9,18,11,22,14,24,11)
)
);

INSERT INTO oswietlenie VALUES(
8,
'L_8',
'LATARNIA 7',
12,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(17, 2, NULL),
NULL,
NULL)
);

INSERT INTO oswietlenie VALUES(
9,
'L_7',
'LATARNIA 7',
12,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(18, 15, NULL),
NULL,
NULL)
);

INSERT INTO oswietlenie VALUES(
10,
'L_7',
'LATARNIA 7',
12,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(15, 18, NULL),
NULL,
NULL)
);

INSERT INTO oswietlenie VALUES(
11,
'L_7',
'LATARNIA 7',
12,
SDO_GEOMETRY(
2001,
NULL, --SRID
SDO_POINT_TYPE(27, 2, NULL),
NULL,
NULL)
);

INSERT INTO drogi_chodniki VALUES(
6,
'CH_A',
'CHODNIK A',
'P£YTY CHODNIKOWE',
SDO_GEOMETRY(
2002,
NULL,
null,
SDO_ELEM_INFO_ARRAY(1, 2, 1),
SDO_ORDINATE_ARRAY(15,1,15,26)
)
);
CREATE INDEX zielen_spatial_index
ON zielen (geometria)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
select * from budynki;


CREATE INDEX drogi_chodniki_spatial_index
ON drogi_chodniki (geometria)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
select * from drogi_chodniki;

CREATE INDEX zielen_spatial_index
ON zielen (geometria)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
select * from zielen;

select id,o.geometria.ST_IsValid()
from drogi_chodniki o
ORDER BY id;

INSERT INTO USER_SDO_GEOM_METADATA VALUES(
'BUDYNKI',
'GEOMETRIA',
SDO_DIM_ARRAY(
SDO_DIM_ELEMENT('X', 0, 29, 0.1),
SDO_DIM_ELEMENT('Y', 0, 19, 0.1)
),
NULL -- SRID
);

INSERT INTO USER_SDO_GEOM_METADATA VALUES(
'DROGI_CHODNIKI',
'GEOMETRIA',
SDO_DIM_ARRAY(
SDO_DIM_ELEMENT('X', 0, 29, 0.1),
SDO_DIM_ELEMENT('Y', 0, 19, 0.1)
),
NULL -- SRID
);

INSERT INTO USER_SDO_GEOM_METADATA VALUES(
'ZIELEN',
'GEOMETRIA',
SDO_DIM_ARRAY(
SDO_DIM_ELEMENT('X', 0, 29, 0.1),
SDO_DIM_ELEMENT('Y', 0, 19, 0.1)
),
NULL -- SRID
);